// constants/index.ts
export const DICT: Record<string, any> = {
  th: {
    searchPlaceholder: "พิมพ์คำค้นหา...",
    advancedSearch: "ค้นหาขั้นสูง",
    addSearchField: "เพิ่มช่องค้นหา",
    quickSelectTitle: "แนะนำหลักสูตรและสาขาวิชาที่มีอยู่ในระบบ:",
    showMajors: "แสดงหลักสูตรทั้งหมด",
    hideMajors: "ซ่อนหลักสูตร",
    found: "พบ",
    items: "รายการ",
    showPerPage: "แสดงหน้าละ",
    searchInResults: "ค้นหาในผลลัพธ์...",
    filterBtn: "ตัวกรองข้อมูล",
    closeFilter: "ซ่อนตัวกรอง",
    sortNewest: "ปีใหม่ - เก่า",
    sortOldest: "ปีเก่า - ใหม่",
    sortAlphaAsc: "ตามตัวอักษร ก-ฮ",
    sortAlphaDesc: "ตามตัวอักษร ฮ-ก",
    filterResource: "ประเภททรัพยากร",
    filterMajor: "สาขาวิชา",
    filterYear: "ปีที่พิมพ์",
    filterAdvisor: "อาจารย์ที่ปรึกษา",
    quick5Years: "5 ปีย้อนหลัง",
    quick10Years: "10 ปีย้อนหลัง",
    yearFrom: "ตั้งแต่ปี",
    yearTo: "ถึงปี",
    searching: "กำลังสืบค้นข้อมูล...",
    noResults: "ไม่พบข้อมูลที่ตรงกับการค้นหา หรือถูกกรองออกหมดแล้ว",
    noYear: "ไม่มีข้อมูลปี",
    accuracy: "ความแม่นยำ",
    viewOnline: "ดูออนไลน์",
    viewOnlineMobile: "ออนไลน์",
    download: "ดาวน์โหลด",
    cite: "อ้างอิง",
    share: "แชร์ลิงก์",
    copied: "คัดลอกแล้ว",
    copyright: "สงวนลิขสิทธิ์ © มหาวิทยาลัยนอร์ทกรุงเทพ",
    page: "หน้า",
    of: "จาก",
    author: "ผู้แต่ง:",
    publishYear: "ปีที่พิมพ์:",
    eduLevel: "ระดับการศึกษา:",
    major: "หลักสูตร/สาขาวิชา:",
    advisor: "อาจารย์ที่ปรึกษา:",
    abstractTh: "บทคัดย่อ (ภาษาไทย)",
    abstractEn: "Abstract (English)",
    keywords: "คำสืบค้น (Keywords):",
    home: "หน้าแรก",
    stats: "สถิติการใช้งาน",
    close: "ปิด",
    siteVisits: "สถิติผู้เข้าชมเว็บไซต์",
    topDownloads: "ยอดดาวน์โหลด",
    topViews: "ยอดเข้าชม",
    timeAll: "รวมทั้งหมด",
    timeMonth: "รายเดือน",
    timeYear: "รายปี",
    times: "ครั้ง",
    monthNames: ["มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนายน", "กรกฎาคม", "สิงหาคม", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม"],
    fromMonth: "ตั้งแต่เดือน",
    toMonth: "ถึงเดือน",
    year: "ปี พ.ศ.",
    fields: {
      all: "ทุกเขตข้อมูล",
      title: "ชื่อเรื่อง",
      author: "ชื่อผู้แต่ง",
      year: "ปีที่พิมพ์",
      major: "สาขาวิชา",
      advisor: "อาจารย์ที่ปรึกษา"
    }
  },
  en: {
    // ใส่ข้อมูล EN เดิมของคุณลงไปตรงนี้...
    searchPlaceholder: "Type to search...",
    advancedSearch: "Advanced Search",
    addSearchField: "Add Field",
    quickSelectTitle: "Recommended Majors in the System:",
    showMajors: "Show All Majors",
    hideMajors: "Hide Majors",
    found: "Found",
    items: "titles",
    showPerPage: "Items per page",
    searchInResults: "Search within...",
    filterBtn: "Filters",
    closeFilter: "Close Filters",
    sortNewest: "Newest - Oldest",
    sortOldest: "Oldest - Newest",
    sortAlphaAsc: "A - Z",
    sortAlphaDesc: "Z - A",
    filterResource: "Resource Type",
    filterMajor: "Major",
    filterYear: "Publish Year",
    filterAdvisor: "Advisor",
    quick5Years: "Last 5 years",
    quick10Years: "Last 10 years",
    yearFrom: "From year",
    yearTo: "To year",
    searching: "Searching database...",
    noResults: "No results found or all filtered out.",
    noYear: "No year data",
    accuracy: "Accuracy",
    viewOnline: "View Online",
    viewOnlineMobile: "Online",
    download: "Download",
    cite: "Cite",
    share: "Share",
    copied: "Copied",
    copyright: "Copyright © North Bangkok University",
    page: "Page",
    of: "of",
    author: "Author:",
    publishYear: "Publish Year:",
    eduLevel: "Education Level:",
    major: "Major:",
    advisor: "Advisor:",
    abstractTh: "Abstract (Thai)",
    abstractEn: "Abstract (English)",
    keywords: "Keywords:",
    home: "Home",
    stats: "Usage Statistics",
    close: "Close",
    siteVisits: "Total Website Visits",
    topDownloads: "Top Downloads",
    topViews: "Top Views",
    timeAll: "All-time",
    timeMonth: "Monthly",
    timeYear: "Yearly",
    times: "times",
    monthNames: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    fromMonth: "From Month",
    toMonth: "To Month",
    year: "Year (B.E.)",
    fields: {
      all: "All Fields",
      title: "Title",
      author: "Author",
      year: "Publish Year",
      major: "Major",
      advisor: "Advisor"
    }
  },
  ch: {
    // ใส่ข้อมูล CH เดิมของคุณลงไปตรงนี้...
    searchPlaceholder: "输入搜索内容...",
    advancedSearch: "高级搜索",
    addSearchField: "添加搜索字段",
    quickSelectTitle: "系统中的推荐专业:",
    showMajors: "显示所有专业",
    hideMajors: "隐藏专业",
    found: "找到",
    items: "标题",
    showPerPage: "每页显示",
    searchInResults: "在结果中搜索...",
    filterBtn: "筛选器",
    closeFilter: "关闭筛选器",
    sortNewest: "最新 - 最旧",
    sortOldest: "最旧 - 最新",
    sortAlphaAsc: "A - Z",
    sortAlphaDesc: "Z - A",
    filterResource: "资源类型",
    filterMajor: "专业",
    filterYear: "出版年份",
    filterAdvisor: "指导老师",
    quick5Years: "近5年",
    quick10Years: "近10年",
    yearFrom: "从年份",
    yearTo: "到年份",
    searching: "正在搜索...",
    noResults: "未找到匹配的数据或已被全部过滤。",
    noYear: "无年份数据",
    accuracy: "准确率",
    viewOnline: "在线查看",
    viewOnlineMobile: "在线的",
    download: "下载",
    cite: "引用",
    share: "分享",
    copied: "已复制",
    copyright: "版权所有 © 曼谷北部大学",
    page: "页",
    of: "/",
    author: "作者:",
    publishYear: "出版年份:",
    eduLevel: "教育水平:",
    major: "专业:",
    advisor: "指导老师:",
    abstractTh: "摘要 (泰文)",
    abstractEn: "摘要 (英文)",
    keywords: "关键词:",
    home: "首页",
    stats: "使用统计",
    close: "关闭",
    siteVisits: "网站总访问量",
    topDownloads: "最高下载",
    topViews: "最高浏览",
    timeAll: "全部时间",
    timeMonth: "每月",
    timeYear: "每年",
    times: "次",
    monthNames: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
    fromMonth: "从月份",
    toMonth: "到月份",
    year: "年份",
    fields: {
      all: "所有字段",
      title: "标题",
      author: "作者",
      year: "出版年份",
      major: "专业",
      advisor: "指导老师"
    }
  }
};

export const MAJOR_MAPPING: Record<string, { en: string, order: number }> = {
  "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาการจัดการ": { en: "Doctor of Philosophy Program in Management", order: 1 },
  "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาการบริหารการศึกษา": { en: "Doctor of Philosophy Program in Educational Administration", order: 2 },
  "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาธุรกิจและทุนมนุษย์": { en: "Doctor of Philosophy Program in Business and Human Capital Development", order: 3 },
  "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาภาษาอังกฤษศึกษา": { en: "Doctor of Philosophy Program in English Language Studies", order: 4 },
  "หลักสูตรบริหารธุรกิจมหาบัณฑิต สาขาวิชาการจัดการ": { en: "Master of Business Administration in Management", order: 5 },
  "หลักสูตรรัฐประศาสนศาสตรมหาบัณฑิต สาขาวิชาการจัดการภาครัฐและเอกชน": { en: "Master of Public Administration Program in Public and Private Management", order: 6 },
  "หลักสูตรรัฐศาสตรมหาบัณฑิต สาขาวิชาการจัดการภาครัฐและเอกชน": { en: "Master of Public Administration Program in Public and Private Management", order: 6 },
  "หลักสูตรศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาธุรกิจและทุนมนุษย์": { en: "Master of Art Program in Business and Human Capital Development", order: 7 },
  "หลักสูตรศิลปศาสตรมหาบัณฑิต สาขาวิชาภาษาอังกฤษศึกษา": { en: "Master of Arts in English Language Studies", order: 8 },
  "หลักสูตรศึกษาศาสตรมหาบัณฑิต สาขาวิชาการบริหารการศึกษา": { en: "Master of Education Program in Educational Administration", order: 9 },
  "หลักสูตรศึกษาศาสตรมหาบัณฑิต สาขาวิชาหลักสูตรและการสอน": { en: "Master of Education Program in Curriculum and Instruction", order: 10 }
};

export const getSearchFields = (t: any) => [
  { value: "all", label: t.fields.all },
  { value: "title", label: t.fields.title },
  { value: "author", label: t.fields.author },
  { value: "year", label: t.fields.year },
  { value: "major", label: t.fields.major },
  { value: "advisor", label: t.fields.advisor }
];